jobs:
  artifacts-url-comments:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: add artifact links to pull request
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: add artifact links to pull request
      uses: tonyhallett/artifacts-url-comments@v1.1.0
      with:
        addTo: pull
        format: "[\U0001F4E6 {name}]({url})"
        prefix: '**To test the changes in this pull request, install this apk:**'
name: add artifact links to pull request
on:
  repository_dispatch:
    types: trigger-ga___artifacts.yml
