jobs:
  build:
    name: Upload Preview APK
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      uses: Swatinem/rust-cache@v2
      with:
        working-directory: jni/deltachat-core-rust
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      uses: android-actions/setup-android@v3
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r23c
    - continue-on-error: true
      env:
        ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
      name: Compile core
      run: 'export PATH="${PATH}:${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/"

        scripts/install-toolchains.sh && scripts/ndk-make.sh

        '
    - continue-on-error: true
      name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Build APK
      run: ./gradlew --no-daemon assembleGplayDebug
    - continue-on-error: true
      name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-preview.apk
        path: build/outputs/apk/gplay/debug/*.apk
name: Upload Preview APK
on:
  repository_dispatch:
    types: trigger-ga___preview-apk.yml
